version: '3.8'

services:
  my-app:
    build:
      context: .  # 현재 디렉토리 (neohuelge)
    ports:
      - "7080:6080"
    environment:
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      SPRING_DATASOURCE_URL: jdbc:oracle:thin:@//oracle:1521/xe
      SPRING_DATASOURCE_USERNAME: yjh
      SPRING_DATASOURCE_PASSWORD: 1234
      JAVA_OPTS: -Duser.timezone=Asia/Seoul
    depends_on:
      - redis
      - oracle

  redis:
    image: redis
    ports:
      - "6379:6379"

  oracle:
    build:
      context: ./Oracle  # Oracle Dockerfile 경로
    environment:
      - ORACLE_PASSWORD=oracle
      - TZ=Asia/Seoul
    ports:
      - "1522:1521"
    volumes:
      - oracle-data:/opt/oracle/oradata

volumes:
  oracle-data:
